// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmcguBHniTiiFAf4YnX3y4lq4ROrbg4xE',
    appId: '1:842463606957:web:2f9da2f6ddeca91c1eee24',
    messagingSenderId: '842463606957',
    projectId: 'instagrim-3ec80',
    authDomain: 'instagrim-3ec80.firebaseapp.com',
    storageBucket: 'instagrim-3ec80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJukc8oZZxQ7dxCAZ9s2GIFdhpth1sKfQ',
    appId: '1:842463606957:android:bd4d9254764dcbe11eee24',
    messagingSenderId: '842463606957',
    projectId: 'instagrim-3ec80',
    storageBucket: 'instagrim-3ec80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexJK7sFIYHjbDIXxmVwbozJ9jhaOjAwM',
    appId: '1:842463606957:ios:69f809b87f4cd70e1eee24',
    messagingSenderId: '842463606957',
    projectId: 'instagrim-3ec80',
    storageBucket: 'instagrim-3ec80.appspot.com',
    iosBundleId: 'com.example.instagrim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexJK7sFIYHjbDIXxmVwbozJ9jhaOjAwM',
    appId: '1:842463606957:ios:b4a83655bfe78f901eee24',
    messagingSenderId: '842463606957',
    projectId: 'instagrim-3ec80',
    storageBucket: 'instagrim-3ec80.appspot.com',
    iosBundleId: 'com.example.instagrim.RunnerTests',
  );
}
